clusterName: YOURCLUSTERHERE
splunkObservability:
  realm: YOURREALMHERE
  accessToken: YOURTOKENHERE

agent:
  config:
    receivers:
      smartagent/redis:    
        type: collectd/redis
        host: redis
        port: 6379
    service:
      pipelines:
        metrics:
          receivers:
            - hostmetrics
            - kubeletstats
            - receiver_creator
            - signalfx
            - smartagent/redis