agent:
  config:
    processors:
      attributes/update:
        actions:
          - key: my.key
            value: redacted
            action: update
    service:
      pipelines:
        traces:
          processors:
            - k8s_tagger
            - batch
            - resource
            - resourcedetection
            - attributes/update
            - resource/add_environment