apiVersion: v1
kind: Pod
metadata:
  name: py-autogen
  namespace: otel
spec:
  containers:
  - name: py-autogen
    image: docker.io/stevelerner/python-autogen
    ports:
    - containerPort: 6379
    env:
    - name: TZ
      value: America/New_York
    - name: REDISHOST
      value: redis
    - name: OTEL_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_SERVICE_NAME
      value: python-autogen-otel
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      value: http://$(OTEL_IP):4317
    command: ["/bin/sh"]
    args: ["run-autogen-ext.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: otel
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: otel
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: docker.io/stevelerner/redis
        ports:
        - containerPort: 6379
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]