agent:
  config:
    receivers:
      prometheus_simple:
        endpoint: "prometheus:9090"
    service:
      pipelines:
        metrics:
          receivers:
            - hostmetrics
            - kubeletstats
            - receiver_creator
            - signalfx
            - prometheus_simple