kubectl delete -n otel deployment flask-server &
kubectl delete -n otel service flask-server &
kubectl delete -n otel pod client-py-gets &
kubectl delete -n otel pod client-py-posts &
kubectl delete -n otel pod client-java-otel-k8s &
kubectl delete -n otel pod redis &
kubectl delete -n otel pod client2-java-otel-k8s &
kubectl delete -n otel pod java-manual-inst-k8s &
kubectl delete -n otel deployment prometheus-endpoint &
kubectl delete -n otel deployment redis &
kubectl delete -n otel service redis &
