---
apiVersion: v1
kind: Pod
metadata:
  name: client-java-otel-k8s
  namespace: otel
spec:
  containers:
  - name: client-java-otel-k8s
    image: docker.io/stevelerner/otel-java
    env:
    - name: OTEL_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_SERVICE_NAME
      value: client-java-otel-k8s
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://$(OTEL_IP):4317
    command: ["/bin/sh"]
    args: ["run-client.sh"]