---
# Flask Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-server
  namespace: otel
spec:
  selector:
    matchLabels:
      name: flask-server
  template:
    metadata:
      labels:
        name: flask-server
    spec:
      containers:
      - name: flask-server
        image: docker.io/stevelerner/otel-python
        ports:
          - name: http
            containerPort: 5000
        env:
        - name: OTEL_SERVICE_NAME
          value: flask-server
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://$(OTEL_IP):4317
        command: ["/bin/sh"]
        args: ["run-flask-redis-server.sh"]
---
# Flask Server Service
apiVersion: v1
kind: Service
metadata:
  name: flask-server
  namespace: otel
spec:
  selector:
    name: flask-server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
# Python Posts Pod
apiVersion: v1
kind: Pod
metadata:
  name: client-py-posts
  namespace: otel
spec:
  containers:
  - name: client-py-posts
    image: docker.io/stevelerner/otel-python
    env:
    - name: OTEL_SERVICE_NAME
      value: client-py-posts
    - name: OTEL_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      value: http://$(OTEL_IP):4317
    command: ["/bin/sh"]
    args: ["run-posts.sh"]
---
# Python Gets Pod
apiVersion: v1
kind: Pod
metadata:
  name: client-py-gets
  namespace: otel
spec:
  containers:
  - name: client-py-gets
    image: docker.io/stevelerner/otel-python
    env:
    - name: OTEL_SERVICE_NAME
      value: client-py-gets
    - name: OTEL_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      value: http://$(OTEL_IP):4317
    command: ["/bin/sh"]
    args: ["run-gets.sh"]
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: otel
spec:
  selector:
    name: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: otel
spec:
  selector:
    matchLabels:
      name: redis
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: docker.io/stevelerner/redis
        ports:
        - containerPort: 6379
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]